# Generated by Django 5.1 on 2024-08-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=500)),
                ('publish', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
